apiVersion: apps/v1
kind: Deployment
metadata:
  Name: reactjs-
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactjs
  template:
    metadata:
      labels:
        app: reactjs
    spec:
      containers:
        - name: frontend
          image: client:0.1.0
          ports:
            - containerPort: 3000
        - name: backend
          image: devconnector:1.0.0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  Name: reactjs-svc-
spec:
  type: LoadBalancer
  selector:
    app: reactjs
  ports:
    - port: 3000
      targetPort: 3000
    - port: 5000
      targetPort: 5000
