apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactjs
  template:
    metadata:
      labels:
        app: reactjs
    spec:
      containers:
        imagePullPolicy: IfNotPresent
        - name: frontend
          image: client:0.1.0
          ports:
            - containerPort: 3000
        - name: backend
          image: devconnector:1.0.0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  type: LoadBalancer
  selector:
    app: reactjs
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: api
      port: 5000
      targetPort: 5000
